// Liste des lignes de bus et leurs destinations
export const defaultBusLines = [
    { number: "02", route: "Cité Fairmont → Gare Marcory" },
    { number: "02", route: "Gare Marcory → Cité Fairmont" },
    { number: "03", route: "Gare Nord → Koumassi Cité Langouste" },
    { number: "03", route: "Koumassi Cité Langouste → Gare Nord" },
    { number: "04", route: "Terminus Attecoube → Gare Marcory" },
    { number: "04", route: "Gare Marcory → Terminus Attecoube" },
    { number: "05", route: "Koumassi Nord-Est → Cité Administrative" },
    { number: "05", route: "Cité Administrative → Koumassi Nord-Est" },
    { number: "06", route: "Aéroport → Gare Sud" },
    { number: "06", route: "Gare Sud → Aéroport" },
    { number: "07", route: "Gare Marcory → Vridi Cité" },
    { number: "07", route: "Vridi Cité → Gare Marcory" },
    { number: "08", route: "Abobo Akeikoi → Gare Nord" },
    { number: "08", route: "Gare Nord → Abobo Akeikoi" },
    { number: "10", route: "Gare Nord → Gare Sud" },
    { number: "10", route: "Gare Sud → Gare Nord" },
    { number: "11", route: "Adjamé Liberté → Koumassi Mesano" },
    { number: "11", route: "Koumassi Mesano → Adjamé Liberté" },
    { number: "12", route: "Gare Nord → Terminus Port-Bouët Phare" },
    { number: "12", route: "Terminus Port-Bouët Phare → Gare Nord" },
    { number: "13", route: "Adjamé Liberté → Hôpital de Koumassi" },
    { number: "13", route: "Hôpital de Koumassi → Adjamé Liberté" },
    { number: "13", route: "Gare Koumassi → Gare Nord" },
    { number: "13", route: "Gare Nord → Gare Koumassi" },
    { number: "14", route: "Terminus Williamsville → Gare Marcory" },
    { number: "14", route: "Gare Marcory → Terminus Williamsville" },
    { number: "15", route: "Gare Abobo → Gare Sud" },
    { number: "15", route: "Gare Sud → Gare Abobo" },
    { number: "16", route: "Djibi Village → Gare Nord" },
    { number: "16", route: "Gare Nord → Djibi Village" },
    { number: "17", route: "Anani → Port de Pêche" },
    { number: "17", route: "Gonzagueville → Vridi Canal" },
    { number: "17", route: "Port de Pêche → Anani" },
    { number: "17", route: "Vridi Canal → Gonzagueville" },
    { number: "18", route: "Gare Sud → Centre Pilote Port-Bouët" },
    { number: "18", route: "Centre Pilote Port-Bouët → Gare Sud" },
    { number: "19", route: "Gare Nord → Vridi Iran" },
    { number: "19", route: "Vridi Iran → Gare Nord" },
    { number: "20", route: "Cité ADO Zone Industrielle → Gare Sud" },
    { number: "20", route: "Gare Sud → Cité ADO Zone Industrielle" },
    { number: "21", route: "École Nationale de Police → CHU Treichville" },
    { number: "21", route: "CHU Treichville → École Nationale de Police" },
    { number: "22", route: "Cinéma Entente Treichville → Gare Nord" },
    { number: "22", route: "Gare Nord → Cinéma Entente Treichville" },
    { number: "23", route: "Gare Koumassi → Vridi Canal" },
    { number: "23", route: "Vridi Canal → Gare Koumassi" },
    { number: "24", route: "CPMA Vridi → Koumassi Nord-Est" },
    { number: "24", route: "Koumassi Nord-Est → CPMA Vridi" },
    { number: "25", route: "Hôtel de Ville Plateau → Koumassi Sicogi" },
    { number: "25", route: "Koumassi Sicogi → Hôtel de Ville Plateau" },
    { number: "26", route: "Gare Koumassi → Gare Nord" },
    { number: "26", route: "Gare Nord → Gare Koumassi" },
    { number: "27", route: "Gare Sud → Yopougon Niangon Sud à gauche" },
    { number: "27", route: "Yopougon Niangon Sud à gauche → Gare Sud" },
    { number: "28", route: "Gare Sud → Riviéra M'pouto" },
    { number: "28", route: "Riviéra M'pouto → Gare Sud" },
    { number: "29", route: "Gare Nord → Port-Bouet derrière Warf" },
    { number: "29", route: "Port-Bouet derrière Warf → Gare Nord" },
    { number: "30", route: "Gare Sud → Yopougon Kouté" },
    { number: "30", route: "Yopougon Kouté → Gare Sud" },
    { number: "35", route: "II Plateaux Vallon → Gare Nord" },
    { number: "35", route: "Gare Nord → II Plateaux Vallon" },
    { number: "36", route: "Gare Nord → Yopougon Abobo Doumé" },
    { number: "36", route: "Yopougon Abobo Doumé → Gare Nord" },
    { number: "38", route: "Yopougon Koweït → Yopougon Micao" },
    { number: "38", route: "Yopougon Micao → Yopougon Koweït" },
    { number: "40", route: "Yopougon Kouté → Gare Sud" },
    { number: "40", route: "Gare Sud → Yopougon Kouté" },
    { number: "41", route: "Adjamé Liberté → Riviéra M'pouto" },
    { number: "41", route: "Riviéra M'pouto → Adjamé Liberté" },
    { number: "42", route: "Abobo Doumé → Yopougon Sideci" },
    { number: "42", route: "Yopougon Sideci → Abobo Doumé" },
    { number: "43", route: "Gare Nord → Yopougon Kouté" },
    { number: "43", route: "Yopougon Kouté → Gare Nord" },
    { number: "44", route: "Abobo Doumé → Yopougon Cité Verte" },
    { number: "44", route: "Yopougon Cité Verte → Abobo Doumé" },
    { number: "45", route: "Abobo PK18 → Gare Nord" },
    { number: "45", route: "Gare Nord → Abobo PK18" },
    { number: "46", route: "Cité Administrative → Yopougon Sideci" },
    { number: "46", route: "Yopougon Sideci → Cité Administrative" },
    { number: "47", route: "Abobo Doumé → Yopougon Attié" },
    { number: "47", route: "Yopougon Attié → Abobo Doumé" },
    { number: "48", route: "Abobo Gendarmerie → Saint Jean" },
    { number: "48", route: "Saint Jean → Abobo Gendarmerie" },
    { number: "49", route: "Gare Abobo → Gare Campus" },
    { number: "50", route: "Gare Nord → Koumassi Terminus Sicogi" },
    { number: "50", route: "Koumassi Terminus Sicogi → Gare Nord" },
    { number: "51", route: "Cité Administrative → Terminus Sagbé" },
    { number: "51", route: "Terminus Sagbé → Cité Administrative" },
    { number: "52", route: "Abobo Sagbé → Campus Cocody" },
    { number: "52", route: "Campus Cocody → Abobo Sagbé" },
    { number: "53", route: "Cité Vridi → Gare Campus" },
    { number: "53", route: "Gare Campus → Gonzagueville" },
    { number: "53", route: "Gare Campus → Vridi Cité" },
    { number: "53", route: "Gonzagueville → Gare Campus" },
    { number: "54", route: "Abobo Gendarmerie → Cité Administrative" },
    { number: "54", route: "Cité Administrative → Abobo Gendarmerie" },
    { number: "56", route: "CHU de Cocody → Koumassi Nord-Est" },
    { number: "56", route: "Koumassi Nord-Est → CHU de Cocody" },
    { number: "58", route: "Adjamé Liberté → Vridi Port de Pêche" },
    { number: "58", route: "Vridi Port de Pêche → Adjamé Liberté" },
    { number: "59", route: "CHU Treichville → Gare Nord" },
    { number: "59", route: "Gare Nord → CHU Treichville" },
    { number: "60", route: "Abobo Gendarmerie → Mairie Anyama" },
    { number: "61", route: "Abobo Pharmacie la Me → Ebimpe" },
    { number: "61", route: "Ebimpe → Abobo Pharmacie la Me" },
    { number: "64", route: "Cocody Blockausso → Gare Nord" },
    { number: "64", route: "Gare Nord → Cocody Blockausso" },
    { number: "67", route: "Anani → Gare Lagunaire Treichville" },
    { number: "67", route: "Gare Lagunaire Treichville → Anani" },
    { number: "67", route: "Gare Lagunaire Treichville → Gonzagueville" },
    { number: "67", route: "Gonzagueville → Gare Lagunaire Treichville" },
    { number: "68", route: "Gare Koumassi → Anani" },
    { number: "75", route: "Abobo Baoulé → Cité Administrative" },
    { number: "75", route: "Cité Administrative → Abobo Baoulé" },
    { number: "76", route: "Abobo PK18 → Cité Administrative" },
    { number: "76", route: "Cité Administrative → Abobo PK18" },
    { number: "77", route: "Abobo Gendarmerie → Carrefour Zone" },
    { number: "77", route: "Abobo Gendarmerie → Micao Zone Industrielle" },
    { number: "77", route: "Carrefour Zone → Abobo Gendarmerie" },
    { number: "77", route: "Micao Zone Industrielle → Abobo Gendarmerie" },
    { number: "78", route: "Gare Nord → Riviéra M'badon" },
    { number: "78", route: "Riviéra M'badon → Gare Nord" },
    { number: "81", route: "Gare Nord → Terminus Angré" },
    { number: "81", route: "Terminus Angré → Gare Nord" },
    { number: "82", route: "Gare Sud → Terminus Angré" },
    { number: "82", route: "Terminus Angré → Gare Sud" },
    { number: "83", route: "École de Police → Gare Nord" },
    { number: "83", route: "Gare Nord → École de Police" },
    { number: "83", route: "Gare Nord → Riviéra Sogefiha" },
    { number: "83", route: "Riviéra Sogefiha → Gare Nord" },
    { number: "84", route: "Cocody Blockausso → Gare Nord" },
    { number: "84", route: "Gare Nord → Cocody Blockausso" },
    { number: "85", route: "Gare Campus → Yopougon Kouté" },
    { number: "85", route: "Gare Campus → Yopougon Phalènes" },
    { number: "85", route: "Yopougon Kouté → Gare Campus" },
    { number: "85", route: "Yopougon Phalènes → Gare Campus" },
    { number: "86", route: "Akouédo Village → Gare Nord" },
    { number: "86", route: "Gare Nord → Akouédo Village" },
    { number: "87", route: "Carrefour la Vie → Terminus Bingerville" },
    { number: "87", route: "Terminus Bingerville → Carrefour la Vie" },
    { number: "90", route: "CHU Angré → Cocody Blockausso" },
    { number: "90", route: "Cocody Angré Djibi → Cocody Blockausso" },
    { number: "90", route: "Cocody Blockausso → CHU Angré" },
    { number: "90", route: "Cocody Blockausso → Cocody Angré Djibi" },
    { number: "91", route: "Adjamé Liberté → Gare Sud" },
    { number: "91", route: "Gare Sud → Adjamé Liberté" },
    { number: "92", route: "Gare Nord → Koumassi Nord-Est" },
    { number: "92", route: "Koumassi Nord-Est → Gare Nord" },
    { number: "616", route: "Abatta Village → Gare Nord Adjamé" },
    { number: "616", route: "Gare Nord Adjamé → Abatta Village" },
    { number: "712", route: "Amondji → Grand Carrefour Koumassi" },
    { number: "712", route: "Grand Carrefour Koumassi → Amondji" },
    { number: "712", route: "Grand Carrefour Koumassi → Yopougon Saint André" },
    { number: "712", route: "Yopougon Saint André → Grand Carrefour Koumassi" },
    { number: "713", route: "Abobo Gendarmerie → Grand Carrefour Koumassi" },
    { number: "713", route: "Grand Carrefour Koumassi → Abobo Gendarmerie" },
    { number: "715", route: "Grand Carrefour Koumassi → Sococe Deux Plateaux" },
    { number: "715", route: "Sococe Deux Plateaux → Grand Carrefour Koumassi" },
    { number: "716", route: "Cocody Riviéra Palmeraie → Grand Carrefour Koumassi" },
    { number: "716", route: "Grand Carrefour Koumassi → Cocody Riviéra Palmeraie" },
    { number: "717", route: "Anani → Hôtel de Ville" },
    { number: "717", route: "Hôtel de Ville → Anani" },
    { number: "718", route: "Adjamé Liberté → Gonzagueville" },
    { number: "718", route: "Gonzagueville → Adjamé Liberté" },
    { number: "719", route: "Angré Terminus 81-82 → Yopougon Saint André" },
    { number: "719", route: "Yopougon Saint André → Angré Terminus 81-82" },
    { number: "720", route: "Cocody Riviéra Palmeraie → Yopougon Saint André" },
    { number: "720", route: "Yopougon Saint André → Cocody Riviéra Palmeraie" },
    { number: "721", route: "CHU Treichville → Riviéra Palmeraie" },
    { number: "721", route: "Riviéra Palmeraie → CHU Treichville" },
    { number: "726", route: "Gare Sud → Yopougon Attié Terminus 47" },
    { number: "726", route: "Yopougon Attié Terminus 47 → Gare Sud" },
    { number: "727", route: "Cocody Saint Jean → Yopougon Saint André" },
    { number: "727", route: "Yopougon Saint André → Cocody Saint Jean" },
    { number: "728", route: "École de Police → Yopougon Lubafrique" },
    { number: "728", route: "Yopougon Lubafrique → École de Police" },
    { number: "729", route: "Cocody Riviéra Palmeraie → Yopougon Koweït" },
    { number: "729", route: "Yopougon Koweït → Cocody Riviéra Palmeraie" },
    { number: "770", route: "Abobo Akeikoi → CHU de Treichville" },
    { number: "770", route: "CHU de Treichville → Abobo Akeikoi" },
    { number: "771", route: "Niangon Sud à Droite → Vridi Iran" },
    { number: "771", route: "Vridi Iran → Niangon Sud à Droite" },
    { number: "772", route: "Abobo PK18 → Vridi Iran" },
    { number: "772", route: "Vridi Iran → Abobo PK18" },
    { number: "773", route: "Bingerville → Gare Sud" },
    { number: "773", route: "Gare Sud → Bingerville" },
    { number: "775", route: "Angré Château → CHU Treichville" },
    { number: "775", route: "CHU Treichville → Angré Château" },
    { number: "79", route: "Abobo Gendarmerie → Adjamé Liberté" },
    { number: "79", route: "Adjamé Liberté → Abobo Gendarmerie" },
    { number: "610", route: "Adjamé Liberté → Bingerville Hopital mère-enfant" },
    { number: "610", route: "Bingerville Hopital mère-enfant → Adjamé Liberté" },
    { number: "701", route: "Angré Château → Terminus 701 km 9" },
    { number: "701", route: "Terminus 701 km 9 → Angré Château" },
    { number: "702", route: "Carrefour la Vie → Cité Eden" },
    { number: "702", route: "Cité Eden → Carrefour la Vie" },
    { number: "704", route: "Abobo Baoulé → Saint Jean" },
    { number: "704", route: "Saint Jean → Abobo Baoulé" },
    { number: "704", route: "Terminus Saint Jean → Angré Château" },
    { number: "704", route: "Angré Château → Terminus Saint Jean" },
    { number: "704", route: "Saint Jean → Dokoui" },
    { number: "708", route: "Carrefour la Vie → Plateau Gare Sud" },
    { number: "708", route: "Plateau Gare Sud → Carrefour la Vie" },
    { number: "705", route: "Riviéra 2 → Angré Château" },
    { number: "705", route: "Angré Château → Riviéra 2" },
    { number: "710", route: "Carrefour la Vie → Abatta Village" },
    { number: "710", route: "Abatta Village → Carrefour la Vie" },
    { number: "710", route: "Terminus Cité des Arts → Terminus Feh Kesse" },
    { number: "710", route: "Terminus Feh Kesse → Terminus Cité des Arts" },
    { number: "94", route: "Cocody Blockausso → Gare Marcory" },
    { number: "94", route: "Gare Marcory → Cocody Blockausso" },
    { number: "201", route: "Abobo PK18 → Hôtel de Ville" },
    { number: "201", route: "Hôtel de Ville → Abobo PK18" },
    { number: "203", route: "Gare Abobo → Gare Sud" },
    { number: "203", route: "Gare Sud → Gare Abobo" },
    { number: "205", route: "Angré Djibi → Gare Sud" },
    { number: "205", route: "Gare Sud → Angré Djibi" },
    { number: "206", route: "Hôtel de Ville → Saint André" },
    { number: "206", route: "Hôtel de Ville → Yopougon Kouté" },
    { number: "206", route: "Saint André → Hôtel de Ville" },
    { number: "206", route: "Yopougon Kouté → Hôtel de Ville" },
    { number: "209", route: "Gare Sud → Yopougon Gandhi" },
    { number: "209", route: "Yopougon Gandhi → Gare Sud" },
    { number: "210", route: "Cocody SCI Les Rosiers → Gare Sud" },
    { number: "210", route: "Gare Sud → Cocody SCI Les Rosiers" },
    { number: "211", route: "Cité Administrative → Terminus Gonzagueville" },
    { number: "211", route: "Terminus Gonzagueville → Cité Administrative" },
    { number: "212", route: "Gare Sud → Niangon Sud à Droite" },
    { number: "212", route: "Niangon Sud à Droite → Gare Sud" },
];

